import esbuild from "esbuild";
import process from "process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

if (!fs.existsSync("output")) {
    fs.mkdirSync("output");
}

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "moment",
        "child_process",
        "fs",
        "os",
        "path",
        "node:events",
        "node:path",
        "node:util",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
    ],
    format: "cjs",
    target: "es2018",
    platform: "browser",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "output/main.js",
    minify: prod,
});

if (prod) {
    await context.rebuild();
    fs.copyFileSync("manifest.json", "output/manifest.json");
    fs.copyFileSync("styles.css", "output/styles.css");
    console.log("Build complete! Output in ./output/");
    process.exit(0);
} else {
    await context.watch();
}
